[package]
name = "valser"
description = "Music player with niche and or useless features"

license = "GPL-3.0-or-later"

repository = "https://github.com/MagicTINTIN/Valser"
documentation = "https://github.com/MagicTINTIN/Valser/wiki"

version = "0.2.2"
edition = "2021"

[package.metadata.release]
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{tag_name}}"]
pre-release-commit-message = "chore(release): {{version}}"
tag-message = "Release {{version}}"
tag-name = "v{{version}}"
sign-tag = false

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_color",
    "bevy_log",
    "default_font",
    "x11",
    "wayland",
] }

android-activity = { version = "0.6", features = ["native-activity"], optional = true }

bevy_egui = "0.39.1"

rand = "0.10.1"
walkdir = "2.5.0"
lofty = "0.24.0" # for tag reading (artist, title, genre)
redb = "4.1.0"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.150"
dirs = "6.0.0"
crossbeam-channel = "0.5.16"


rodio = { version = "*", default-features = false, features = [
    "playback",
    "symphonia-all",
    "symphonia-ogg",
    "symphonia-mkv",
] }

symphonia = { version = "0.5", default-features = false, features = ["ogg"] }
symphonia-adapter-libopus = "0.2"

# the following doesn't work as cpal-shared-stdcxx doesn't exist in 0.22 (only 0.21 which isn't compatible with my soft)

# [target.'cfg(target_os = "android")'.dependencies.rodio]
# version = "*"
# default-features = false
# features = ["playback", "symphonia-all", "cpal-shared-stdcxx"]

# [target.'cfg(not(target_os = "android"))'.dependencies.rodio]
# version = "*"
# default-features = false
# features = ["playback", "symphonia-all"]



[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.17.1"
mpris-server = "0.10.0"
smol = "2.0.2"
futures = "0.3.32"

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1"
jni = "0.21"

# Android-specific
# [target.'cfg(target_os = "android")'.dependencies]
# cpal-shared-stdcxx fixes C++ stdlib linking on Android
# rodio already pulls in cpal, this just adds the feature