apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    namespace "fr.magictintin.valser"

    defaultConfig {
        applicationId "fr.magictintin.valser"
        minSdkVersion 28
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.games:games-activity:3.0.1'
}